# .goreleaser.yml
version: 2
project_name: wstunnel

before:
  hooks:
    - go mod tidy

builds:
  - binary: wstunnel
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goarch:
      - amd64
      - arm64
      - 386
    goos:
      - darwin
      - windows
      - linux
      - android
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: 386
      - goos: darwin
        goarch: 386
      - goos: android
        goarch: amd64
      - goos: android
        goarch: 386
    ldflags:
      - -s -w -X main.VV="wstunnel_{{.Version}}_{{.Date}}_{{.Commit}}"

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README*
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

changelog:
  use: git # or github
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  draft: false
  prerelease: auto
  mode: replace
  header: |
    See [CHANGELOG.md](CHANGELOG.md) for all changes.
  footer: |
    **Full Changelog**: https://github.com/rshade/wstunnel/blob/main/CHANGELOG.md

snapshot:
  name_template: "{{ incpatch .Version }}-next"

# Optional Docker configuration
# dockers:
#   - image_templates:
#     - "ghcr.io/username/wstunnel:{{ .Version }}"
#     - "ghcr.io/username/wstunnel:latest"